### ISSUE TITLE
プロフィールにGoogle+のリンクが残っている

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/Hayaemon_Web#12]
2019年4月に一般ユーザー向けGoogle+サービスは終了したので、
プロフィールに残っているGoogle+のリンクは消しても良いのでは?
![無題](https://user-images.githubusercontent.com/50232313/89730453-a1e10c80-da79-11ea-9a7e-f05e6efe6374.jpg)

**Comment by arigayas** [comment]
Webサイトを良くしようとして途中で止まってます(汗)。

**Comment by ryotayama** [comment]
ありがとう、削除しといた！👍
