### ISSUE TITLE
ダウンロード完了画面のリンクをTwitterへのリンクに

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/Hayaemon_Web#13]
http://hayaemon.jp/thanks.html
のユーザコミュニティへのリンクはHTTP ERROR 500になるので、
Twitterへのリンクにするのはどうでしょうか?
![無題](https://user-images.githubusercontent.com/50232313/89730832-53357180-da7d-11ea-8d04-0de0b0eb9609.jpg)

**Comment by ryotayama** [comment]
クランベリーさん、ありがとう！🙏
直しといた！👍
