### ISSUE TITLE
hayaemon.jp をHTTPS化したい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Web#4]
hayaemon.jp をHTTPS化したいです

**Comment by sugartarou** [comment]
Amazon Linux AMIにおける公式手順
https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-ami.html

**Comment by sugartarou** [comment]
Amazon Linux AMI公式手順にはLets Encryptoの詳細手順が載ってないので自分でなんとかする。
certbotを入れたい：https://eff-certbot.readthedocs.io/en/stable/install.html
・yum：Amazon Linux ami 2018は古すぎてリポジトリがサポート切れてて存在しない。
・python pip：これならいける。
```bash
sudo yum install -y python38
sudo yum install -y python38-devel
sudo yum install -y python38-tools
sudo yum install -y libffi-devel
sudo pip-3.8 install --upgrade pip
sudo ln -s /usr/local/bin/pip /usr/bin/pip
sudo pip install certbot  certbot-apache
```
ここまでやってcertbotは入ったが、動かそうと思ったらopensslが1.1.1以上じゃないとダメって怒られた。
<details>
例のごとくAmazon Linux ami 2018が古いのでyumからopenssl1.1.1は入れられず。
以下に載ってた方法で入れた。
https://askubuntu.com/questions/1102803/how-to-upgrade-openssl-1-1-0-to-1-1-1-in-ubuntu-18-04

```bash
wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz
tar zxf openssl-1.1.1g.tar.gz
cd openssl-1.1.1g
./config
mkdir ~/backup_ssl
sudo mv /usr/bin/openssl ~/backup_ssl/
sudo make install
sudo ln -s /usr/local/bin/openssl /usr/bin/openssl
sudo ldconfig
```

ここまででopenssl1.1.1がインストールできたと思いきや、ライブラリが見えないと言い出す。

```bash
$ openssl version
/usr/local/openssl/bin/openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

以下の解決策をやっても状況変わらず。
https://qiita.com/centos1205/items/24326ff0e7b886354898

あきらめて以下を/etc/profileに書いた。

```bash
# for OpenSSL 1.1.1
export LD_LIBRARY_PATH="/usr/local/lib64:${LD_LIBRARY_PATH}"
```

これでようやく1.1.1とご対面。

```bash
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020
```

</details>
openssl 1.1.1を入れてみてしまったが、よく考えたらurllib3のバージョンを落とせばいいだけだった。

```bash
sudo pip install urllib3==1.26.15
```

これをしただけで解決。

**Comment by sugartarou** [comment]
以下の通りに証明書取得、設定。
https://webree.jp/article/letsencrypt-install/

**Comment by sugartarou** [comment]
3カ月後が証明書の期限
2024/5/23

とりあえずcronで自動更新を仕掛けておく。
5月に自動更新されて8/23になればOK
```
$ sudo crontab -l
# SSL証明書自動更新
00 04 10 * * certbot renew
```

**Comment by sugartarou** [comment]
AWSのセキュリティグループのインバウンドルールに443の解放設定を追加して無事開通
https://hayaemon.jp/

**Comment by sugartarou** [comment]
http⇒httpsのrewrite設定書いてMixed-Contentエラーもできる限りは取ったのでOK
クローズします

証明書自動更新されなかったらまた別issue切る。
