### ISSUE TITLE
index.html の一番下にある「マニュアル詳細」の画像ファイルの位置がおかしい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon_Web#5]
http://hayaemon.jp/index.html  の一番下にある「マニュアル詳細」についてです。

![image](https://user-images.githubusercontent.com/11251874/43382568-1fcafade-9413-11e8-8b20-43544e36343d.png)

赤枠で囲ったこのボタン画像が文字列の前にあるのは、このページのここだけなのですが、これを「マニュアル詳細」の後ろに動かすとCSSでの指定が減らせるので動かしても良いでしょうか？

**Comment by ryotayama** [comment]
OKです₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
#6 にて対応した。
