### ISSUE TITLE
アセットファイルが足りない

### ISSUE THREAD

**Issue by ryutaro** [ryotayama/Hayaemon_Web#8]
画像などのアセットファイルが不足しているためで正常に動作するか確認できません

**Comment by arigayas** [comment]
### index.html

- http://hayaemon.jp/images/hayaemonscreenshot2_s.jpg
- http://hayaemon.jp/images/hayaemonscreenshot_s.jpg
- http://hayaemon.jp/download_windows_japanese.png
- http://hayaemon.jp/download_windows_english.png
- http://hayaemon.jp/download_macos.png
- http://soft.edolfzoku.com/link/freesoft.png
- http://soft.edolfzoku.com/link/hayaemon-L.gif
- http://hayaemon.jp/face.png
- http://hayaemon.jp/mail.png はフォントにするつもりです。

**Comment by ryutaro** [comment]
mail.pngもdiffとる上で必要じゃない？

**Comment by arigayas** [comment]
なるほど。
そういうことなら必要ですね。
修正します。　→　修正しました。

**Comment by arigayas** [comment]
## 右列のメニュー

### http://hayaemon.jp/about.html

- http://hayaemon.jp/images/hayaemonscreenshot3_s.jpg
- http://hayaemon.jp/music.png

動画が再生出来るということを示すスクリーンショットですが映画の画像になっているので
新しくスクリーンショットを作成した方が良い気がします。

背景画像の http://hayaemon.jp/music.png は無くても良い気がします。
_個人的には背景画像があると読みにくい箇所があるので_

### http://hayaemon.jp/environment.html

- http://hayaemon.jp/pc.png 背景画像

### http://hayaemon.jp/manual.html
追記すべき画像無し

### http://hayaemon.jp/bosyu.html

- http://hayaemon.jp/develop.png 背景画像

背景画像の人を良太さんに変えるのが良いと思います。

**Comment by arigayas** [comment]
## 右列の「ボーカルチェンジ」
### http://hayaemon.jp/morainaki.html

- http://hayaemon.jp/morainakiback.jpg 背景画像
- http://hayaemon.jp/morainaki.jpg

### http://hayaemon.jp/heavyrotation.html

- http://hayaemon.jp/heavyrotationback.jpg 背景画像　TOKIOが4人になったから変更が必要
- http://hayaemon.jp/heavyrotation.jpg

## 右列の「聞々ハヤえもん オンラインマニュアル」1
### http://hayaemon.jp/howtodownload.html

- http://hayaemon.jp/toppage.png 更新が必要
- http://hayaemon.jp/nihongo.png 更新が必要

### http://hayaemon.jp/boot.html

- http://hayaemon.jp/extract.png 
- http://hayaemon.jp/firstboot.png

### http://hayaemon.jp/play.html

- http://hayaemon.jp/play.png 背景画像
- http://hayaemon.jp/clickfile.png
- http://hayaemon.jp/clickopenbutton.png
- http://hayaemon.jp/clickexplorer.png

### http://hayaemon.jp/changespeed.html
http://hayaemon.jp/changespeedback.png 背景画像(何故この画像？)
http://hayaemon.jp/manual/contents/changespeed.png

### http://hayaemon.jp/whychangespeed.html
### http://hayaemon.jp/changefrequency.html
### http://hayaemon.jp/changepitch.html

画像無し

### http://hayaemon.jp/savefile.html

- http://hayaemon.jp/savefileback.jpg 背景画像(何故この画像？)
- http://hayaemon.jp/savefile.jpg
- http://hayaemon.jp/saveall.jpg

**Comment by arigayas** [comment]
## 右列の「聞々ハヤえもん オンラインマニュアル」2
### http://hayaemon.jp/abloop.html
### http://hayaemon.jp/controls.html
### http://hayaemon.jp/lyrics.html
### http://hayaemon.jp/effects.html
### http://hayaemon.jp/playrange.html
### http://hayaemon.jp/incspeed.html
### http://hayaemon.jp/eqpreset.html
### http://hayaemon.jp/soundeffects.html
### http://hayaemon.jp/normalize.html
### http://hayaemon.jp/vocalcancel.html
### http://hayaemon.jp/reverse.html
### http://hayaemon.jp/record.html
画像無し


### http://hayaemon.jp/versionup.html

- http://hayaemon.jp/versionupback.png 背景画像
- http://hayaemon.jp/extract.png
- http://hayaemon.jp/versionup.png

### http://hayaemon.jp/uninstall.html

- http://hayaemon.jp/gomibako.png 背景画像

以上です。

**Comment by arigayas** [comment]
チェック漏れがあったので追加

### http://hayaemon.jp/donate.html

- http://hayaemon.jp/donate.png 背景画像

### http://hayaemon.jp/thanks.html

- http://hayaemon.jp/headphone.png 背景画像

### http://hayaemon.jp/introduce.html

- http://hayaemon.jp/introduce.png 背景画像
